### ISSUE TITLE
Not reading json columns from Postgres?

### ISSUE THREAD

**Issue by hiteshjasani** [wishlife/defsql#1]
I've just started playing around with the library because I like the direction you're heading with the focus on simplicity.  Was wondering if you feel json is supported in the library?  I have a simple table with a doc column of type jsonb.

Trying to do a query results in

``` clojure
(defquery select-all-test-table [] "select * from demo_test")

;; [{:id 4, :name "wendy", :country nil, :doc #object[org.postgresql.util.PGobject 0x21d8bcbe "{\"age\": 35, \"tags\": [\"red\", \"restaurant\"]}"]}]
```

There are a number of different ways people have solved this but was wondering if there is a way built in to defsql that I don't know about?

**Comment by tendant** [comment]
Simple answer: rowfn and Macro defrow and is designed for this. 

Example: 

``` clojure
;; First, define a ResultSet function using defrow: 
(defrow DemoTestResult [^Long id ^String name ^String country ^:json doc]

;; Second, use ResultSet function:
(defquery select-all-test-table [] {:row rs->DemoTestResult} "select * from demo_test")
```

Note: jsonb type is introduced in Postgres 9.4. The support for jsonb is not built in yet. So you can't really use defrow in your example.

However you can create your own rs->DemoTestResult function. 

Below is the example on how to create such function:

``` clojure
(defn rs->MyUser [^ResultSet rs]
      (new MyUser
           (.getLong rs 1)
           (keyword (.getString rs 2))
           (cheshire.core/parse-string (.getString rs 3) 3)))
```

**Comment by hiteshjasani** [comment]
Great, just what I needed to know.

This is my current setup (along with the defrow and defquery you showed above) and it all works for my simple testing.  I haven't needed to define my own result set mapping function yet.

``` clojure
(definsert into-test-table [^String name ^String country ^:json doc]
  "insert into demo_test(name,country,doc) values(:name, :country, :doc::jsonb)")
```

The only thing that hasn't worked is trying to use the defrow mapper with definsert.

``` clojure
(definsert into-test-table [^String name ^String country ^:json doc]
  {:row rs->DemoTestResult} "insert into demo_test(name,country,doc) values(:name, :country, :doc::jsonb)")

; java.lang.IllegalArgumentException: unknown options: :row
```

But that's not a important to me since all I usually want is the `:id` from inserts.  I was just testing it to see how it handled it.

Looking forward to seeing some of the ideas from your ClojureConj talk in future releases.  Thanks!

**Comment by tendant** [comment]
{:row rowfn} is not supported in current version yet. I have a local version which supports {:row rowfn} for definsert. I will publish it, once I am done with testing.
